### ISSUE TITLE
Grammatical error in Documentation - 'A' to 'An'

### ISSUE THREAD

**Issue by techieshouvik** [techieshouvik/Sorting-Visualizer#1]
The **first line** of Readme.md has a grammatical error<br>
Line - **A** easy to use Sorting Visualizer Tool for Educational Use.<br>
Should be changed to Line - **An** easy to use Sorting Visualizer Tool for Educational Use.
<br>
<b>Go to file : </b><a href="https://github.com/techieshouvik/Sorting-Visualizer/blob/README.md">Readme.md</a>

**Comment by SudhanshuBlaze** [comment]
Hi, I am a newbie. I am looking forward for my first Open Source contribution. Please assign this to me.

**Comment by techieshouvik** [comment]
> Hi, I am a newbie. I am looking forward for my first Open Source contribution. Please assign this to me.

Hey! Good to hear from you! Sure, _You have been assigned the task to resolve this issue_. You can now **Fork the Repo**, make the change and **Create a Pull Request**! 
I would also request you to give a Star to the Project which would be highly appreciated by us.

**Comment by techieshouvik** [comment]
Hi Folks! This is Issue has now been Closed. Kudos to @SudhanshuBlaze ! Happy Coding :)
