### ISSUE TITLE
Make the preloader smaller and Fade Out 

### ISSUE THREAD

**Issue by techieshouvik** [techieshouvik/Sorting-Visualizer#13]
A Preloader should appear for 2 sec before the page loads. 
#The preloader will be decided from codepen once the task is assigned#

You will be guided if needed.

**Comment by AymKh** [comment]
does it have to be 2 sec, or just until the elements load ?

**Comment by techieshouvik** [comment]
In this case 2sec because, the page loads pretty fast, so the preloader cannot be seen at all if we put it in until page load scenario.

**Comment by AymKh** [comment]
https://codepen.io/Marina_Os/pen/wvKGVVX
Maybe one of those....?

**Comment by techieshouvik** [comment]
Great Job @AymKh ! Its working perfect. I have one suggestion , the preloader size is too big, it can be smaller and after 2 secs it will look cleaner if it fades out so thats one thing you can try to do 😄 .  Otherwise, great work!

**Comment by techieshouvik** [comment]
@AymKh  Great work!! The preloader issue has been solved now! Kudos to you 😄 ... Great Enthusiasm!
